package com.lihan.leagueoflegends.feature.champion.domain.model

enum class Language(val code: String) {
    AE("ar_AE"),
    US("en_US"),
    CZ("cs_CZ"),
    DE("de_DE"),
    GR("el_GR"),
    AU("en_AU"),
    GB("en_GB"),
    PH("en_PH"),
    SG("en_SG"),
    AR("es_AR"),
    ES("es_ES"),
    MX("es_MX"),
    FR("fr_FR"),
    HU("hu_HU"),
    IT("it_IT"),
    JP("ja_JP"),
    KR("ko_KR"),
    PL("pl_PL"),
    BR("pt_BR"),
    RO("ro_RO"),
    RU("ru_RU"),
    TH("th_TH"),
    TR("tr_TR"),
    VN("vi_VN"),
    CN("zh_CN"),
    MY("zh_MY"),
    TW("zh_TW")
}
